ASP.NET Core MVC/Project - All Labs/Lab2/Controllers/DepartmentController.cs
using Lab2.Data;
using Lab2.Models;
using Lab2.Repositries.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab2.Controllers
{
    [Authorize(Roles = "Instructor")]
    public class DepartmentController : Controller
    {
        IUnitOfWork unitOfWork; 
        public DepartmentController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var allDepartments = unitOfWork.Department.GetAll().ToList();
            return View(allDepartments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Department.Add(department);
                unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var department = unitOfWork.Department.GetOne(e => e.Id == id);
            if (department == null)
                return NotFound("There No Departments!");
            return View(department);            
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var department = unitOfWork.Department.GetOne(e => e.Id == id);
            if (department == null)
                return NotFound("There No Departments!");
            return View(department);
        }

        [HttpPost]
        public IActionResult Edit(int id, Department department)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Department.Edit(department);
                unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var department = unitOfWork.Department.GetOne(e => e.Id == id);
            if (department == null)
                return NotFound("There No Departments!");
            
            unitOfWork.Department.Remove(department);
            unitOfWork.Complete();
            return RedirectToAction("Index");
        }
    }
}

ASP.NET Core MVC/Project - All Labs/Lab2/Controllers/TestController.cs
using Lab2.Models.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using static System.Net.Mime.MediaTypeNames;

namespace Lab2.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DownloadFile()
        {
            return File("~/MyFile.txt", "text/plain", "FileDownloaded");
        }

        public IActionResult ReturnJson()
        {
            var jsonContent = new { Id = 1, Name = "Abdallah Mostafa", Age = 24 };
            return Json(jsonContent);   
        }

        public IActionResult Google()
        {
            return Redirect("https://www.google.com");
        }

        [MyExceptionFilter]
        public IActionResult ActionFilter()
        {
            // This Will Throw Exception
            int x = int.Parse("abc");  
            return Content(x.ToString());
        }
        static bool flag = false;
        public IActionResult ChangeLayout()
        {
            if (!flag)
            {
                TempData["Layout"] = "_Layout2";
                flag = true;
            }
            else
            {
                TempData["Layout"] = "_Layout";
                flag = false;
            }
            return View("Index");
        }
    }
}

ASP.NET Core MVC/Project - All Labs/Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test</a>
                        </li>
                        
                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Logout  @User.Identity.Name</a>
                            </li>
                            if (User.IsInRole("Instructor"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                                </li>
                            }
                            else if (User.IsInRole("Student"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                                </li>
                            }
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Lab2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET Core MVC/Project - All Labs/Lab2/Views/Shared/_Layout2.cshtml
<html>
    <head>
        <title>My Layout</title>
    </head>
    <body>
        <h1>Header</h1><hr />
        @RenderBody()
        <hr />
        <h3>Footer</h3>
    </body>
</html>